---
# all:
#  hosts:
#    el-instance:
#      ansible_host: 51.250.96.220
#  vars:
#    ansible_connection: ssh
#    ansible_user: vagrant
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 51.250.108.187
kibana:
  hosts:
    ki-instance:
      ansible_host: 51.250.111.163
filebeat:
  hosts:
    application:
      ansible_host: 51.250.111.163
